name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # needed for Sonar analysis

      # -------- Sonar Scan --------
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # -------- Trivy File Scan --------
      - name: Trivy File Scan
        run: trivy fs . > trivyfs.txt

      # -------- Docker Build & Push --------
      - name: Docker Build and Push
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: raunakrao/swiggy-clone-b              # make sure repo exists in Docker Hub
          registry: docker.io
          tags: latest, main-${{ github.sha }}         # tagging to allow trivy scan
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -------- Trivy Image Scan --------
      - name: Trivy Image Scan
        run: trivy image docker.io/raunakrao/swiggy-clone-b:main-2a5a08b > trivyimage.txt
