name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # needed for Sonar analysis

      # -------- Sonar Scan --------
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # -------- Trivy File Scan --------
      - name: Trivy File Scan
        run: trivy fs . > trivyfs.txt

      # -------- Docker Build & Push --------
      - name: Docker Build and Push
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: raunakrao/swiggy-clone-b
          registry: docker.io
          tags: latest, main-${{ github.sha }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -------- Trivy Image Scan --------
      - name: Trivy Image Scan
        run: trivy image docker.io/raunakrao/swiggy-clone-b:latest > trivyimage.txt


  Deploy:
    needs: build     # you wrote build-analyze-scan, but since job name is build, I kept "build"
    runs-on: self-hosted

    steps:
      - name: Update kubeconfig
        run: aws eks --region ap-northeast-1 update-kubeconfig --name virtualtechbox-cluster

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment-and-service.yml

      - name: Send a Slack Notification
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#github-actions'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
